### ISSUE TITLE
fatal or failed error_message are not displayed in stdout

### ISSUE THREAD

**Issue by shaofanhan** [ansible/ansible-runner-service#100]
ansible-runner stdout donot display fatal or failed error_message, but it is displayed when using ansible command.

- ansible-runner stdout below
![image](https://user-images.githubusercontent.com/16680069/133880579-cfee866d-6599-45fc-994b-129f6befe022.png)

- ansible command output below
![image](https://user-images.githubusercontent.com/16680069/133880603-6766fc22-b692-4479-a998-71172213f695.png)

**Comment by mnecas** [comment]
Isn't this ansible-runner runner issue not ansible-runner-service?

**Comment by shaofanhan** [comment]
> Isn't this ansible-runner runner issue not ansible-runner-service?

The image above is stdout content which is in ansible-runner-service artifacts directory.
I wonder how to fix it. To make runner stdout display the fatal error messages.

**Comment by mnecas** [comment]
Please transfer this issue to the https://github.com/ansible/ansible-runner they might know more about it.
