### ISSUE TITLE
Passing hosts through Post to run a playbook

### ISSUE THREAD

**Issue by aswenson24** [ansible/ansible-runner-service#13]
anisble-runner allows you to send hosts
--hosts HOSTS         Define the set of hosts to execute against
I'd like to be able to pass these in as well as part of the POST to run a playbook. 

I know i can modify/add groups and hosts but having to manage this when multiple entities can call into the REST server at the same time doesn't seem possible.

**Comment by jmolmo** [comment]
> anisble-runner allows you to send hosts
> --hosts HOSTS Define the set of hosts to execute against
> I'd like to be able to pass these in as well as part of the POST to run a playbook.
> 
> I know i can modify/add groups and hosts but having to manage this when multiple entities can call into the REST server at the same time doesn't seem possible.

@aswenson24 : You can use the "limit" keyword to execute a playbook only for these hosts.

example:

/api/v1/playbooks/<playbook_name>?limit=<hos1>,<host2>,,,, <hostn> 

Is this what you want to do?

**Comment by aswenson24** [comment]
This is helpful. Are other keywords documented somewhere or should i look at the code? 

I'd really like to pass the host and credentials as we will sometimes have new machines added that are not part of the hosts file and may go away/change (VMs).

However if i can use (POST hosts/{host_name}/groups/{group_name}[?others=group2,group3] ) to add new hosts then i can now use limit to specify which one so that will work. I can also use an Ansible script to copy the ssh id over. Finally i can remove it when i'm done through REST as well.

Some of these machines are VMs and they will come and go so if the Playbook had the ability to specify the host and creds that would be ideal. However it does look like i'll be able to handle it all with what is currently offered. Thanks!

**Comment by jmolmo** [comment]
> This is helpful. Are other keywords documented somewhere or should i look at the code?
> 
Well, you also can pass "extravars" to the ansible playbook using a query string. You can find some useful examples in:
https://github.com/jmolmo/ceph/blob/master/src/pybind/mgr/ansible/ansible_runner_svc.py

You are right. We need to document this better. I will modify the dcoumentation to include examples with the limit keyword, and the use of the url query string to add "extravars"

> I'd really like to pass the host and credentials as we will sometimes have new machines added that are not part of the hosts file and may go away/change (VMs).
> 
Credentials... do you mean to pass user/password? Maybe not a good idea, but maybe we can try to improve addition of hosts providing a public ssh key. In this way only the first connection need user/password. We can copy the Ansible Runner Service public key to the new host to make access to it from the ARS server passwordless.
Please, feel free to comment/improve/rebate this idea.


> However if i can use (POST hosts/{host_name}/groups/{group_name}[?others=group2,group3] ) to add new hosts then i can now use limit to specify which one so that will work. I can also use an Ansible script to copy the ssh id over. Finally i can remove it when i'm done through REST as well.
> 

Agree with you. Use the ARS public key to provide passwordless access from the ARS server to any new host.
 
> Some of these machines are VMs and they will come and go so if the Playbook had the ability to specify the host and creds that would be ideal. However it does look like i'll be able to handle it all with what is currently offered. Thanks!

I think we should avoid to use credentials each time we execute a playbook. Better to provide passwordless access to it if the hosts has been previosly added to the inventory. 


You are welcome! Thanks to you for your ideas and suggestions. And as you know ... contributions are welcome. :-)

**Comment by aswenson24** [comment]
Thanks again jmolmo.
It would be nice to have a way to supply creds through REST. I agree no need for it on each call to playbook but the first connection as you described above for a new host would be great.
My other concerns around adding a host that had me open this are resolved, thank you. Should i close this and open another for a way to pass creds through REST for a new host and include your text above? Using an Ansible script is possible but would IMO be better as part of the REST service.
I was also going to suggest that it would be really handy to be able to upload new Ansible scripts through REST but again i could write an Ansible playbook for this.
I'm pretty new to python but i'd love to contribute when i'm able. Thanks!

**Comment by jmolmo** [comment]
You're welcome.

I think that if it is possible is good that the person who opens the issue will be the one that closes it. So go ahead with it. :-)
I will add two new feature issues to discuss how implement the credentials supply for new hosts and the possibility to upload new playbooks using the REST service.

**Comment by aswenson24** [comment]
Thanks for all the help and information!
Using "?limit=" is exactly what i needed and resolves this issue for me.
Thanks!
