### ISSUE TITLE
sample runner-service docker image needs updating

### ISSUE THREAD

**Issue by pcuzner** [ansible/ansible-runner-service#14]
ceph-ansible now hardcodes an ansible 2.8 dependency, and the current example container is using 2.7. This mismatch causes any testing with ceph-ansible to fail.

Can you please refresh the container image with ansible 2.8

**Comment by jmolmo** [comment]
Solved with:
https://github.com/ansible/ansible-runner-service/pull/15

A new container image based in this modification has been uploaded to:
https://hub.docker.com/r/jolmomar/ansible_runner_service
