### ISSUE TITLE
": No such file or directory" while running the build image 

### ISSUE THREAD

**Issue by rarenicks** [ansible/ansible-runner-service#2]
Followed all the step mentioned at [misc/docker/readme](https://github.com/ansible/ansible-runner-service/blob/master/misc/docker/README.md) and build the image. 

While trying to run the image to create container, I am getting error : ": No such file or directory" 

I doubted that may be the file defined in ENTRYPOINT ie. "/usr/local/bin/ansible_runner_service" was not present so I replaced "/usr/local/bin/ansible_runner_service" with "/bin/bash" and tried running the image and /usr/local/bin/ansible_runner_service was present there. 

So I tried executing the command from bash inside the container "ansible_runner_service" from "/usr/local/bin" dir and got the same error :  ": No such file or directory"

![image](https://user-images.githubusercontent.com/13811957/50482898-15521980-0a0f-11e9-9b9a-12512f36e8a5.png)

**Comment by pcuzner** [comment]
@rarenicks Apologies for the delay during the christmas/new year period.

The idea behind the container is to use it with volume bindings to the hosts filesystem - this is where runner-server would pick up  the playbooks/roles/library etc. In your case, running without volumes hit missing directories in /usr/share/ansible-runner-service within the container.

Can you rebuild the container with the dockerfile in the docker-fix branch and let me know if this resolves the issue?

**Comment by pcuzner** [comment]
Closing issue. PR merged to address the problem and no response from the reporter.
