### ISSUE TITLE
Remove Paramiko dependency

### ISSUE THREAD

**Issue by jmolmo** [ansible/ansible-runner-service#24]
We are using Paramiko just to check if contact with external servers is possible or not. Probably this can be done using a "ping" playbook, and thus avoid this dependency (security problems) and just rely in what Ansible provides to make this kind of check.

**Comment by pcuzner** [comment]
Talking to Matt, it may be easier to use a runner call directly to verify connectivity

**Comment by pcuzner** [comment]
resolved in #29
