### ISSUE TITLE
How does multiple tags support in URL

### ISSUE THREAD

**Issue by yapengwu** [ansible/ansible-runner-service#27]
I tried to input multiple tags in the URL, it returns "Invalid tag syntax". Do you have example to input multiple tags?

**Comment by jmolmo** [comment]
It should work using something like:

`curl -k -i --key ./client.key --cert ./client.crt -H "Content-Type: application/json" --data '{"time_delay":20}' https://localhost:5001/api/v1/playbooks/test_jmo.yml/tags/one,two,three -X POST`

I have confirmed it does not work. Fix on-going

**Comment by yapengwu** [comment]
Tested the fix, it works well.

**Comment by pcuzner** [comment]
closing as fix now merged #28
