### ISSUE TITLE
Race condition in start playbook

### ISSUE THREAD

**Issue by machacekondra** [ansible/ansible-runner-service#47]
When there are two parallel calls to start playbook, it may happen that the first and also the second call passes the line which cleans the artifacts directory. So later whatever playbook first created this directory is executed correctly, but the second playbook is not because it's using the data of the first playbook.

There are few options how to solve it:

1) Make sure the start playbook is synchronized.
2) Use different `private_data_dir` for each ansible playbook call. Internally ansible-runner can use the temp dir, if this directory is not specified, which could be the solution.

**Comment by corester** [comment]
Hi, I discovered the same difficulties in a slightly different way. In a long playbook run the variables of the second playbook are injected in to the first run. Might be the same problem. Hopefully the` private_data_dir`option will fix it.

**Comment by mwperina** [comment]
This should be resolved by https://github.com/ansible/ansible-runner-service/pull/52
