### ISSUE TITLE
Client to API authentication should use mutual TLS

### ISSUE THREAD

**Issue by pcuzner** [ansible/ansible-runner-service#8]
Current client to API auth is based on basic http auth and web token. This design is problematic since it requires user credentials to be stored in a secure manner on the api server. 

An alternate approach is to use TLS server + client authentication (mutual TLS). Implementing a new authentication mechanism also provides an opportunity to review the role of the flask dev server within the solution.

Options Considered
1. Stay with flask, and override the werkzeug request handler to provide the client cert object within the stand request handling process
2. remove the embedded server, and run the flask app within an app container (uwsgi) fronted by a production grade web server (nginx)

**Comment by pcuzner** [comment]
Of the two options, moving to a more production aligned implementation is the preferred path. Assigning to JuanMi to pick up the implementation tasks.

**Comment by jmolmo** [comment]
Implemented in https://github.com/ansible/ansible-runner-service/pull/9
