### ISSUE TITLE
Wirting to log file

### ISSUE THREAD

**Issue by idenkov** [ansible/ansible-runner-service#81]
Hello,

Very nice service and job you are doing, I have one question. 
When running ansible from cli it does write to the log file, but when I run it through the API it does not.
Is there a way to change that and log actions from the API?

Thank you!

**Comment by mnecas** [comment]
Hi,
AFAIK it should log always from API but if you have some issues you can check out https://github.com/ansible/ansible-runner-service/blob/master/logging.yaml
which is located in /etc/ansible-runner-service/logging.yaml
