### ISSUE TITLE
Sending limit to API service

### ISSUE THREAD

**Issue by idenkov** [ansible/ansible-runner-service#82]
Hey,

I am testing the service, but it seems to me it is not possible to send "limit" parameter.
When added to the payload the service does not send it to ansible and roles are applied to all the invetory.

 `POST /api/v1/playbooks/base.yml, parms={'limit': '127.0.0.1'}`
This is what I am seeing in the logs coming to the service, and that playbook run on every host in the inventory.

How can I send either invetory or limit to the playbooks to target specific hosts?

**Comment by jmolmo** [comment]
> Hey,
> 
> I am testing the service, but it seems to me it is not possible to send "limit" parameter.
> When added to the payload the service does not send it to ansible and roles are applied to all the invetory.
> 
> `POST /api/v1/playbooks/base.yml, parms={'limit': '127.0.0.1'}`
> This is what I am seeing in the logs coming to the service, and that playbook run on every host in the inventory.
> 
> How can I send either invetory or limit to the playbooks to target specific hosts?

Limit works .. but use an IP address different from the IPv4 loopback standar address :-) ( it applies to every node).
Another possibility.. use inventory groups including the hosts where you want to execute a playbook.

**Comment by idenkov** [comment]
> > Hey,
> > I am testing the service, but it seems to me it is not possible to send "limit" parameter.
> > When added to the payload the service does not send it to ansible and roles are applied to all the invetory.
> > `POST /api/v1/playbooks/base.yml, parms={'limit': '127.0.0.1'}`
> > This is what I am seeing in the logs coming to the service, and that playbook run on every host in the inventory.
> > How can I send either invetory or limit to the playbooks to target specific hosts?
> 
> Limit works .. but use an IP address different from the IPv4 loopback standar address :-) ( it applies to every node).
It was just an example, I am sending real ip.

**Comment by idenkov** [comment]
Also I am not seeing how to add hosts through the API, the /hosts endpoint does not accept POST requests.
How do I manage the hosts?

**Comment by mnecas** [comment]
@idenkov for adding hosts please check the `/api/v1/groups/<group_name>` section in /api

**Comment by idenkov** [comment]
@mnecas Thank you! Will take a look.
